-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 21:45:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AppDevWebII
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AppDevWebII
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AppDevWebII` DEFAULT CHARACTER SET utf8 ;
USE `AppDevWebII` ;

-- -----------------------------------------------------
-- Table `AppDevWebII`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppDevWebII`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AppDevWebII`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AppDevWebII`.`Disciplinas` (
  `idDisciplinas` INT NOT NULL AUTO_INCREMENT,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idDisciplinas`),
  INDEX `fk_Disciplinas_Users_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Disciplinas_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `AppDevWebII`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
